name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  geolocator: ^10.1.0
  fluttertoast: ^8.2.4
  http: ^1.1.2
  sleek_circular_slider: ^2.0.1
  intl: ^0.19.0
  geocoding: ^2.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

